# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d1:6d:c4:9c:91:18:d5:a9:b3:f8:37:3c:33:0a:05:78"
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
